backend:
  name: github
  repo: letuan20/InnomizeTech.com
  branch: master

media_folder: static/assets
public_folder: assets
collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: hashtags, label: Hashtags, widget: string }
      - { name: title, label: Title }
      - { name: author, label: Author }
      - { name: position, label: Position }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }
  - name: casestudies
    label: Case Studies
    folder: content/case-studies
    create: true
    fields:
      - { name: path, label: Path }
      - { name: technologies, label: Technologies, widget: markdown }
      - { name: devops, label: DevOps, widget: markdown }
      - { name: project, label: Project }
      - { name: client, label: Client }
      - { name: location, label: Location }
      - { name: architecture, label: Position }
      - { name: thumbnail, label: Thumbnail, widget: image }
      - { name: body, label: Body, widget: markdown }
      - { name: featuredImage, label: Project Images, widget: markdown }

