backend:
  name: github
  repo: letuan20/InnomizeTech.com
  branch: master

media_folder: static/assets
public_folder: assets
collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Hashtags, widget: string}
      - { name: title, label: Title }
      - { name: author, label: Author }
      - { name: position, label: Position }
      - { name: image, label: Image, widget: image }
      - { name: body, label: Body, widget: markdown }